spring.application.name=api-compra

# URL de conexão JDBC para o Oracle
# ? CORREÇÃO: Removido o 'url=' duplicado.
spring.datasource.url=jdbc:oracle:thin:@//192.168.1.16:1521/orclpdb.localdomain

# Usuário e senha do banco
spring.datasource.username=compras_app
spring.datasource.password=compras_app

# Driver do Oracle
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Configurações do JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
